import * as React from 'react';
import Template from '../../templates/base';


const PrivacyPolicy = () => {

    return (
        <Template>
            <section className="bg-gradient-to-r from-red-400 min-h-screen p-12">

                <div className="bg-white border border-black w-1/2 m-auto py-12">

                    <p className="w-2/3 m-auto text-3xl mb-12">Privacy Policy</p>

                    <p className="w-2/3  m-auto leading-8">
                        General Data Protection Regulation (GDPR) Privacy Policy for Google Analytics

                        Our website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.

                        Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.

                        Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.

                        Users have the right to access, correct, and delete any personal data that is collected through Google Analytics. If you would like to exercise this right, please contact us using the contact information provided on our website. Additionally, if you would like to opt-out of Google Analytics tracking, you can do so by using the Google Analytics opt-out browser add-on.

                        We will update this Privacy Policy from time to time. The updated version will be effective as soon as it is accessible. We encourage you to review this Privacy Policy regularly to stay informed about how we are protecting the personal information we collect.

                        This Policy was last updated on 28-01-2023
                    </p>
                </div>
            </section>
        </Template>
    )
}

export default PrivacyPolicy;
